### ISSUE TITLE
Logrotate config defaults

### ISSUE THREAD

**Issue by olifre** [voxpupuli/puppet-logrotate#118]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.5.3
- Ruby: AIO packages
- Distribution: Ubuntu 18.04
- Module version: v3.2.2-rc0

## How to reproduce (e.g Puppet code you use)
```
class { '::logrotate':
 ensure => 'latest',
 config => { dateext         => true, },
}
```

## What are you seeing
Sensible OS defaults from https://github.com/voxpupuli/puppet-logrotate/blob/master/manifests/params.pp are not applied anymore if any `config` is specified. These defaults are crucial at least on Ubuntu, where `su_user` and `su_group` are essential. 

## What behaviour did you expect instead
I expected the defaults to be used as base, extended / overwritable with user options, i.e.:
```
config => merge($::logrotate::params::conf_params, $logrotate_our_config),
```
I'm using now as workaround exactly that, preceded by:
```
        if ! defined(Class['::logrotate::params']) {
                include ::logrotate::params
        }
```
i.e. using the params class manually.

**Comment by vegarnilsen** [comment]
I'm having the same issue with Puppet 6 and v3.4.0 of this module.

```bash
clsvegar@test02:~$ /opt/puppetlabs/bin/puppet --version
6.0.4
clsvegar@test02:~$ sudo /opt/puppetlabs/bin/puppet module list | grep logrotate
├── puppet-logrotate (v3.4.0)
```

I have this config in Hiera, and none of the default `su*` parameters for Ubuntu 18.04 are used:

```yaml
logrotate::config:
  dateext: true
  dateformat: '.upto-%Y%m%d'
  compress: true
  delaycompress: true
```

To have a working config, I have to add these lines as well:

```yaml
  su: true
  su_user: 'root'
  su_group: 'syslog'
```
